"use client";

import Image from "next/image";
import Link from "next/link";
import { ArrowDownRight, ArrowUpRight } from "lucide-react";
import { API_BASE_URL } from "@/services/authService";
import ContactSection from "./ContactSection";

const portrait = `${API_BASE_URL}/static/uploads/4e0a62f8-a2e5-4eb8-9f9e-88cb0819e66c.jpg`;
const work = [
  { no: "01", accent: "lime", label: "Enterprise · Murata", title: "Enterprise RAG knowledge platform", body: "Built the complete RAG environment and delivery pipeline: automated internal announcements, document transformation, retrieval, backend APIs, CRUD, access management, and department-level controls.", tags: "AI / RAG / FastAPI / MongoDB" },
  { no: "02", accent: "orange", label: "Manufacturing data", title: "MES text-to-SQL agent", body: "Enabled employees to query MES data in natural language, safely translate intent into SQL, and turn results into charts—without waiting for analysts or writing database queries.", tags: "LLM / SQL / MES / Visualization" },
];
const products = [
  ["AI learning studio", "A full-stack platform for teams to learn from internal material with notes, quizzes, and searchable transcripts."],
  ["Secure e-stamping", "Batch document stamping with coordinated placement, certificate encryption, SSO, audit trails, and approval rules."],
  ["Real-time translation", "Internal translation with context scaling and AI correction, reducing communication friction between Taiwanese and Japanese teams."],
];

export default function EditorialLanding() {
  return <>
    <section id="hero" className="relative min-h-[94vh] overflow-hidden bg-[#1b1c1f] text-[#f4f3ef]">
      <div className="mx-auto grid min-h-[94vh] max-w-[1500px] grid-cols-1 items-center px-6 pb-12 pt-28 md:grid-cols-[1.25fr_.75fr] md:px-10 lg:px-16">
        <div className="relative z-10 pt-14 md:pt-0"><p className="mb-6 font-mono text-[10px] uppercase tracking-[.32em] text-white/35">Portfolio / 2026</p><h1 className="text-[clamp(4.4rem,10vw,10.5rem)] font-medium uppercase leading-[.83] tracking-[-.075em]">Angelo<br />Angelo</h1><div className="mt-9 flex items-center gap-8"><p className="font-mono text-[10px] uppercase leading-[1.6] tracking-[.16em] text-white/55">Enterprise knowledge<br />Manufacturing data<br />Workflow automation</p><a href="#portfolio" className="flex h-20 w-20 items-center justify-center rounded-full bg-[#455ce9] font-mono text-[9px] uppercase tracking-[.12em] transition-transform hover:scale-110">View work</a></div></div>
        <div className="relative mt-16 h-[54vh] min-h-[440px] overflow-hidden md:mt-0 md:h-[70vh]"><Image src={portrait} alt="Angelo portrait" fill priority className="object-cover grayscale contrast-110" sizes="(min-width:768px) 42vw,100vw" /></div>
      </div><p className="absolute bottom-6 right-8 hidden font-mono text-[9px] uppercase tracking-[.22em] text-white/35 md:block">Scroll to explore</p>
    </section>

    <section id="about" className="relative overflow-hidden bg-[#f2f0e9] px-6 py-24 text-[#17181a] md:px-10 lg:py-32"><div className="absolute -right-16 top-10 h-64 w-64 rounded-full bg-[#dcff62]/40 blur-3xl" /><div className="mx-auto max-w-5xl"><p className="mb-5 font-mono text-[9px] uppercase tracking-[.28em] text-[#758f2d]">01 / About me · Based in Taiwan</p><div className="grid gap-12 md:grid-cols-[1.35fr_.75fr]"><div><h2 className="text-[clamp(3.5rem,7vw,7rem)] font-medium uppercase leading-[.86] tracking-[-.065em]">I build AI<br />for the<br />factory floor.</h2><div className="mt-9 grid gap-6 border-t border-black/15 pt-5 sm:grid-cols-2"><p className="font-mono text-[11px] font-semibold uppercase">Murata<br />Manufacturing<br /><span className="font-normal text-black/40">AI applications & DX</span></p><p className="text-sm leading-6 text-black/65">I turn manufacturing problems into secure, production-ready AI products—owning the path from discovery and architecture to full-stack delivery, rollout, and continuous improvement.</p></div></div><div className="relative h-[480px] overflow-hidden rounded-lg md:h-auto"><Image src={portrait} alt="Angelo at work" fill className="object-cover" sizes="(min-width:768px) 32vw,100vw" /><span className="absolute bottom-4 right-4 rounded-full bg-[#dfff58] px-4 py-2 font-mono text-[9px] font-bold text-black">AI / DX</span></div></div><div className="mt-12 grid border-t border-black/15 sm:grid-cols-3">{[["90%","Internal users"],["Multi-dept.","Production adoption"],["TW ↔ JP","Cross-team systems"]].map(([v,l])=><div key={v} className="border-b border-black/15 py-6 sm:border-r sm:px-6 first:pl-0 last:border-r-0"><p className="text-2xl font-semibold uppercase">{v}</p><p className="mt-1 font-mono text-[9px] uppercase tracking-[.16em] text-black/40">{l}</p></div>)}</div></div></section>

    <section id="skills" className="bg-[#151714] px-6 py-24 text-[#f1f0ea] md:px-10 lg:py-32"><div className="mx-auto max-w-5xl"><div className="grid gap-12 lg:grid-cols-[.55fr_1fr]"><p className="pt-3 font-mono text-[9px] uppercase tracking-[.26em] text-[#a7c84b]">Experience · Murata<br /><span className="text-white/30">AI applications & digital transformation</span></p><h2 className="text-[clamp(3.6rem,7vw,7rem)] font-medium uppercase leading-[.84] tracking-[-.065em]">From<br />prototype<br />to production.</h2></div><div id="portfolio" className="mt-20 grid border-t border-white/10 md:grid-cols-2">{work.map((item)=><article key={item.no} className="border-b border-white/10 py-10 md:border-r md:px-8 first:pl-0 last:border-r-0"><div className={`mb-14 h-1 w-8 ${item.accent === "lime" ? "bg-[#c4e94e]" : "bg-[#ff6244]"}`} /><p className="font-mono text-[9px] uppercase tracking-[.2em] text-white/30">{item.label}</p><h3 className="mt-5 text-3xl font-semibold uppercase leading-[.95] tracking-[-.04em]">{item.title}</h3><p className="mt-6 max-w-md text-sm leading-6 text-white/50">{item.body}</p><p className="mt-8 font-mono text-[8px] uppercase tracking-[.15em] text-white/30">{item.tags}</p></article>)}</div><div className="mt-16"><p className="font-mono text-[9px] uppercase tracking-[.2em] text-white/30">Products / Platforms / Automation</p><h3 className="mt-3 text-3xl font-semibold uppercase">More products shipped.</h3><div className="mt-6 grid border-l border-t border-white/10 md:grid-cols-3">{products.map(([title,body])=><article key={title} className="min-h-56 border-b border-r border-white/10 p-6"><h4 className="text-sm font-semibold uppercase">{title}</h4><p className="mt-5 text-xs leading-5 text-white/45">{body}</p></article>)}</div></div><div className="mt-14 grid border-t border-white/10 pt-6 md:grid-cols-[.55fr_1fr]"><p className="font-mono text-[9px] uppercase leading-4 tracking-[.18em] text-[#a7c84b]">Beyond product delivery<br /><span className="text-lg text-white">I also help teams choose, adopt, and learn the right tools.</span></p><ul className="mt-8 md:mt-0">{["Python crawlers and RPA for daily business operations","Custom GPT, GPU infrastructure, and M365 license evaluation","Agentic workflows for equipment test-code generation","Monthly digital knowledge sharing and internal workshops"].map(x=><li key={x} className="flex justify-between border-b border-white/10 py-3 text-xs text-white/55">{x}<ArrowDownRight size={13}/></li>)}</ul></div></div></section>

    <section id="blog" className="min-h-[70vh] bg-[#101113] px-6 py-28 text-white md:px-10"><div className="mx-auto max-w-5xl"><div className="mb-20 text-center"><p className="font-mono text-[9px] uppercase leading-5 tracking-[.18em] text-white/35">Products, experiments, and technical exploration I continue to build outside my work at Murata.</p><p className="mt-4 font-mono text-[8px] uppercase tracking-[.2em] text-white/20">Personal work · Challenges / Solutions / Results</p></div><Link href="/blog" className="group grid items-center border-y border-white/10 py-8 md:grid-cols-[.1fr_1fr_.2fr]"><span className="font-mono text-[9px] text-white/25">01</span><div><h2 className="text-3xl font-semibold tracking-tight">智慧點餐助手</h2><p className="mt-2 font-mono text-[8px] uppercase tracking-[.15em] text-white/30">Smart restaurant ordering assistant</p></div><span className="mt-4 flex items-center justify-end gap-3 font-mono text-[8px] uppercase tracking-[.18em] text-white/30 md:mt-0">Case study <ArrowUpRight size={14}/></span></Link></div></section>
    <ContactSection />
  </>;
}
