import { API_BASE_URL } from './authService'; // Re-use API_BASE_URL

export interface HeroSettings {
  _id?: string; // Optional, as it's generated by MongoDB
  settings_id: string;
  hero_background_image_url?: string;
  hero_personal_photo_url?: string;
  hero_main_title: string;
  hero_subtitle: string;
  hero_bio_content: string;
  hero_button_1_label: string;
  hero_button_2_label: string;
}

export const DEFAULT_HERO_SETTINGS: HeroSettings = {
  settings_id: 'hero_settings',
  hero_personal_photo_url: '/placeholder.jpg',
  hero_main_title: 'Angelo Developer',
  hero_subtitle: 'Creative Developer',
  hero_bio_content: 'Based in Taiwan, creating premium digital experiences with a focus on motion and interaction.',
  hero_button_1_label: 'View Work',
  hero_button_2_label: 'Contact Me',
};

async function getErrorMessage(response: Response, fallback: string): Promise<string> {
  try {
    const errorData = await response.json();
    return errorData.detail || fallback;
  } catch {
    return fallback;
  }
}

export interface SiteSettings {
  _id?: string;
  settings_id: string;
  contact_email: string;
  contact_phone: string;
  contact_location: string;
  social_github: string;
  social_instagram: string;
  social_youtube: string;
  portfolio_title: string;
  portfolio_subtitle: string;
  blog_title: string;
  nav_brand_primary: string;
  nav_brand_secondary: string;
  nav_mobile_caption: string;
  nav_home_label: string;
  nav_about_label: string;
  nav_skills_label: string;
  nav_portfolio_label: string;
  nav_blog_label: string;
  nav_contact_label: string;
  intro_splash_enabled: boolean;
  intro_splash_keywords: string;
  section_hero_enabled: boolean;
  section_hero_order: number;
  section_about_enabled: boolean;
  section_about_order: number;
  section_skills_enabled: boolean;
  section_skills_order: number;
  section_portfolio_enabled: boolean;
  section_portfolio_order: number;
  section_blog_enabled: boolean;
  section_blog_order: number;
  section_contact_enabled: boolean;
  section_contact_order: number;
  about_image_url: string;
  about_eyebrow: string;
  about_title: string;
  about_summary: string;
  about_body: string;
  about_photo_caption: string;
  stat_1_value: string;
  stat_1_label: string;
  stat_2_value: string;
  stat_2_label: string;
  stat_3_value: string;
  stat_3_label: string;
  focus_1_label: string;
  focus_1_title: string;
  focus_1_body: string;
  focus_2_label: string;
  focus_2_title: string;
  focus_2_body: string;
  focus_3_label: string;
  focus_3_title: string;
  focus_3_body: string;
  skills_eyebrow: string;
  skills_title: string;
  skills_stack_label: string;
  skills_core_stack: string;
  skills_default_description: string;
  skills_frontend_description: string;
  skills_backend_description: string;
  skills_collaboration_description: string;
  skills_analytics_description: string;
  portfolio_kicker: string;
  portfolio_empty_eyebrow: string;
  portfolio_empty_title: string;
  portfolio_empty_body: string;
  portfolio_item_button_label: string;
  portfolio_default_tag: string;
  blog_subtitle: string;
  blog_empty_eyebrow: string;
  blog_empty_title: string;
  blog_empty_body: string;
  blog_item_button_label: string;
  blog_draft_label: string;
  detail_blog_back_label: string;
  detail_blog_eyebrow: string;
  detail_blog_not_found: string;
  detail_portfolio_back_label: string;
  detail_portfolio_eyebrow: string;
  detail_portfolio_not_found: string;
  contact_title: string;
  contact_intro_label: string;
  contact_location_label: string;
  contact_name_label: string;
  contact_name_placeholder: string;
  contact_email_label: string;
  contact_email_placeholder: string;
  contact_message_label: string;
  contact_message_placeholder: string;
  contact_submit_label: string;
  contact_submitting_label: string;
  contact_socials_label: string;
  contact_footer_note: string;
  contact_footer_stack: string;
  contact_local_time_label: string;
}

let siteSettingsCache: SiteSettings | null = null;
let siteSettingsCacheTime = 0;
let siteSettingsRequest: Promise<SiteSettings> | null = null;
const SITE_SETTINGS_CACHE_TTL_MS = 30_000;

/**
 * Fetches the Hero section settings from the backend.
 * @returns A Promise that resolves to HeroSettings.
 */
export async function getHeroSettings(): Promise<HeroSettings> {
  try {
    const response = await fetch(`${API_BASE_URL}/api/settings/hero`, {
      method: 'GET',
      headers: {
        'Content-Type': 'application/json',
      },
    });

    if (!response.ok) {
      throw new Error(await getErrorMessage(response, 'Failed to fetch hero settings'));
    }

    return response.json();
  } catch {
    return DEFAULT_HERO_SETTINGS;
  }
}

/**
 * Updates the Hero section settings in the backend.
 * Requires an admin JWT token for authorization.
 * @param settings - The HeroSettings object to update.
 * @param token - The JWT access token for authentication.
 * @returns A Promise that resolves to the updated HeroSettings.
 */
export async function updateHeroSettings(settings: HeroSettings, token: string): Promise<HeroSettings> {
  const response = await fetch(`${API_BASE_URL}/api/settings/hero`, {
    method: 'PUT',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${token}`,
    },
    body: JSON.stringify(settings),
  });

  if (!response.ok) {
    throw new Error(await getErrorMessage(response, 'Failed to update hero settings'));
  }

  return response.json();
}

export async function getSiteSettings(): Promise<SiteSettings> {
  if (siteSettingsCache && Date.now() - siteSettingsCacheTime < SITE_SETTINGS_CACHE_TTL_MS) {
    return siteSettingsCache;
  }

  if (!siteSettingsRequest) {
    siteSettingsRequest = (async () => {
      const response = await fetch(`${API_BASE_URL}/api/settings/site`, {
        method: 'GET',
        headers: {
          'Content-Type': 'application/json',
        },
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.detail || 'Failed to fetch site settings');
      }

      const settings: SiteSettings = await response.json();
      siteSettingsCache = settings;
      siteSettingsCacheTime = Date.now();
      return settings;
    })().finally(() => {
      siteSettingsRequest = null;
    });
  }

  return siteSettingsRequest;
}

export async function updateSiteSettings(settings: SiteSettings, token: string): Promise<SiteSettings> {
  const response = await fetch(`${API_BASE_URL}/api/settings/site`, {
    method: 'PUT',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${token}`,
    },
    body: JSON.stringify(settings),
  });

  if (!response.ok) {
    const errorData = await response.json();
    throw new Error(errorData.detail || 'Failed to update site settings');
  }

  const updatedSettings: SiteSettings = await response.json();
  siteSettingsCache = updatedSettings;
  siteSettingsCacheTime = Date.now();
  return updatedSettings;
}
