"use client";

import { useEffect, useMemo, useState } from "react";
import { Check, Mail, RefreshCw, Reply, Trash2 } from "lucide-react";
import { ContactItem, deleteContact, getContactsAdmin, updateContactStatus } from "@/services/contactService";
import { getErrorMessage } from "@/services/apiClient";
import { AdminAlert, AdminPanel, ConfirmDialog, EmptyState, primaryButton, SearchField, StatusBadge } from "@/components/admin/shell/AdminUi";

export default function ContactManager() {
  const [contacts, setContacts] = useState<ContactItem[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [query, setQuery] = useState(""); const [filter, setFilter] = useState("unread"); const [deletingItem, setDeletingItem] = useState<ContactItem | null>(null);
  const refresh = async () => { const token = localStorage.getItem("authToken"); if (!token) return setError("登入已失效，請重新登入。"); try { setLoading(true); setError(null); setContacts(await getContactsAdmin(token)); } catch (cause) { setError(getErrorMessage(cause, "無法載入聯絡訊息。")); } finally { setLoading(false); } };
  useEffect(() => { void refresh(); }, []);
  const filtered = useMemo(() => contacts.filter(item => (filter === "all" || (filter === "unread" && !item.read) || (filter === "replied" && item.replied)) && `${item.name} ${item.email} ${item.message}`.toLowerCase().includes(query.toLowerCase())), [contacts, filter, query]);
  const updateStatus = async (item: ContactItem, updates: { read?: boolean; replied?: boolean }) => { const token = localStorage.getItem("authToken"); if (!token) return; try { const updated = await updateContactStatus(item.id, updates, token); setContacts(current => current.map(contact => contact.id === item.id ? updated : contact)); } catch (cause) { setError(getErrorMessage(cause, "無法更新訊息狀態。")); } };
  const remove = async () => { if (!deletingItem) return; const token = localStorage.getItem("authToken"); if (!token) return; try { await deleteContact(deletingItem.id, token); setContacts(current => current.filter(contact => contact.id !== deletingItem.id)); } catch (cause) { setError(getErrorMessage(cause, "無法刪除訊息。")); } finally { setDeletingItem(null); } };
  return <><AdminPanel><div className="flex flex-col gap-3 border-b border-zinc-200 p-5 lg:flex-row lg:items-center lg:justify-between"><div className="flex flex-col gap-3 sm:flex-row"><SearchField value={query} onChange={setQuery} placeholder="搜尋寄件人、信箱或內容" /><select value={filter} onChange={event => setFilter(event.target.value)} className="rounded-lg border border-zinc-200 bg-white px-3 py-2 text-sm text-zinc-700 outline-none focus:border-zinc-400"><option value="unread">未讀</option><option value="replied">已回覆</option><option value="all">所有訊息</option></select></div><button onClick={() => void refresh()} className={primaryButton}><RefreshCw size={16} />重新整理</button></div>{error && <div className="px-5 pt-5"><AdminAlert>{error}</AdminAlert></div>}{loading ? <EmptyState title="正在載入收件匣…" description="請稍候。" /> : filtered.length === 0 ? <EmptyState title={query ? "沒有符合的訊息" : "收件匣目前沒有訊息"} description={query ? "試試其他關鍵字。" : "新的聯絡表單會顯示在這裡。"} /> : <div className="divide-y divide-zinc-100">{filtered.map(item => <article key={item.id} className={`p-5 transition hover:bg-zinc-50 ${!item.read ? "bg-indigo-50/30" : ""}`}><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h2 className="font-semibold normal-case tracking-tight text-zinc-950">{item.name}</h2>{!item.read && <StatusBadge tone="warning">未讀</StatusBadge>}{item.replied && <StatusBadge tone="success">已回覆</StatusBadge>}</div><a href={`mailto:${item.email}`} className="mt-1 inline-flex items-center gap-1 text-sm text-[#455ce9] hover:underline"><Mail size={14} />{item.email}</a><p className="mt-3 max-w-3xl whitespace-pre-wrap text-sm leading-6 text-zinc-600">{item.message}</p><p className="mt-3 text-xs text-zinc-400">{new Date(item.created_at).toLocaleString("zh-TW", { hour12: false })}</p></div><div className="flex shrink-0 items-center gap-1"><button onClick={() => void updateStatus(item, { read: !item.read })} className="rounded-lg p-2 text-zinc-500 hover:bg-zinc-100 hover:text-zinc-950" aria-label={item.read ? "標記未讀" : "標記已讀"}>{item.read ? <Mail size={17} /> : <Check size={17} />}</button><button onClick={() => void updateStatus(item, { read: true, replied: !item.replied })} className="rounded-lg p-2 text-zinc-500 hover:bg-zinc-100 hover:text-zinc-950" aria-label={item.replied ? "取消已回覆" : "標記已回覆"}><Reply size={17} /></button><button onClick={() => setDeletingItem(item)} className="rounded-lg p-2 text-zinc-500 hover:bg-red-50 hover:text-red-600" aria-label={`刪除 ${item.name} 的訊息`}><Trash2 size={17} /></button></div></div></article>)}</div>}</AdminPanel><ConfirmDialog open={Boolean(deletingItem)} title="刪除訊息？" description={`來自 ${deletingItem?.email || ""} 的訊息將永久移除。`} onCancel={() => setDeletingItem(null)} onConfirm={() => void remove()} /></>;
}
