"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Power, Trash2 } from "lucide-react";
import { deleteSubscriber, getSubscribers, NewsletterSubscriber, setSubscriberActive } from "@/services/newsletterService";
import { getErrorMessage } from "@/services/apiClient";
import { AdminAlert, AdminPanel, ConfirmDialog, EmptyState, SearchField, StatusBadge, tableCell, tableHeader } from "@/components/admin/shell/AdminUi";

export default function NewsletterManager() {
  const [subscribers, setSubscribers] = useState<NewsletterSubscriber[]>([]); const [error, setError] = useState<string | null>(null); const [query, setQuery] = useState(""); const [deletingItem, setDeletingItem] = useState<NewsletterSubscriber | null>(null);
  const refresh = useCallback(async () => { try { setError(null); setSubscribers(await getSubscribers(localStorage.getItem("authToken") || "")); } catch (cause) { setError(getErrorMessage(cause, "無法載入訂閱者。")); } }, []);
  useEffect(() => { void refresh(); }, [refresh]);
  const filtered = useMemo(() => subscribers.filter(item => `${item.email} ${item.source}`.toLowerCase().includes(query.toLowerCase())), [subscribers, query]);
  const toggle = async (subscriber: NewsletterSubscriber) => { try { const updated = await setSubscriberActive(subscriber.id, !subscriber.active, localStorage.getItem("authToken") || ""); setSubscribers(items => items.map(item => item.id === updated.id ? updated : item)); } catch (cause) { setError(getErrorMessage(cause, "無法更新訂閱者狀態。")); } };
  const remove = async () => { if (!deletingItem) return; try { await deleteSubscriber(deletingItem.id, localStorage.getItem("authToken") || ""); setSubscribers(items => items.filter(item => item.id !== deletingItem.id)); } catch (cause) { setError(getErrorMessage(cause, "無法刪除訂閱者。")); } finally { setDeletingItem(null); } };
  return <><AdminPanel><div className="flex flex-col gap-3 border-b border-zinc-200 p-5 sm:flex-row sm:items-center sm:justify-between"><SearchField value={query} onChange={setQuery} placeholder="搜尋信箱或來源" /><span className="text-sm text-zinc-500">{subscribers.filter(item => item.active).length} 位有效訂閱者</span></div>{error && <div className="px-5 pt-5"><AdminAlert>{error}</AdminAlert></div>}{filtered.length === 0 ? <EmptyState title={query ? "沒有符合的訂閱者" : "還沒有訂閱者"} description="新的訂閱會顯示在這裡。" /> : <div className="overflow-x-auto"><table className="min-w-full"><thead className="border-b border-zinc-200 bg-zinc-50"><tr><th className={tableHeader}>電子信箱</th><th className={tableHeader}>來源</th><th className={tableHeader}>狀態</th><th className={`${tableHeader} text-right`}>操作</th></tr></thead><tbody className="divide-y divide-zinc-100">{filtered.map(item => <tr key={item.id} className="hover:bg-zinc-50"><td className={`${tableCell} font-medium text-zinc-900`}>{item.email}</td><td className={tableCell}>{item.source}</td><td className={tableCell}><StatusBadge tone={item.active ? "success" : "neutral"}>{item.active ? "有效" : "已停用"}</StatusBadge></td><td className={`${tableCell} whitespace-nowrap text-right`}><button onClick={() => void toggle(item)} className="rounded-lg p-2 text-zinc-500 hover:bg-zinc-100 hover:text-zinc-950" aria-label={item.active ? "停用訂閱者" : "啟用訂閱者"}><Power size={17} /></button><button onClick={() => setDeletingItem(item)} className="ml-1 rounded-lg p-2 text-zinc-500 hover:bg-red-50 hover:text-red-600" aria-label={`刪除 ${item.email}`}><Trash2 size={17} /></button></td></tr>)}</tbody></table></div>}</AdminPanel><ConfirmDialog open={Boolean(deletingItem)} title="刪除訂閱者？" description={`${deletingItem?.email || ""} 將從訂閱名單永久移除。`} onCancel={() => setDeletingItem(null)} onConfirm={() => void remove()} /></>;
}
